# Generated by Django 4.2.11 on 2024-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0007_job_jobapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
